import { ApolloProvider } from '@parkease/network/src/config/apollo'
import '@parkease/ui/src/app/globals.css'
import { Container } from '@parkease/ui/src/components/atoms/Container'
import { SessionProvider } from '@parkease/ui/src/components/molecules/SessionProvider'
import { Header } from '@parkease/ui/src/components/organisms/Header'
import { MenuItem } from '@parkease/util/types'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Parkease',
  description: 'Generated by create next app',
}

const MENUITEMS: MenuItem[] = [
  { label: 'Search', href: '/search' },
  { label: 'Bookings', href: '/bookings' },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <SessionProvider>
      <ApolloProvider>
        <html lang="en">
          <body className="bg-gray-25">
            <Header menuItems={MENUITEMS} />
            <Container> {children}</Container>
          </body>
        </html>
      </ApolloProvider>
    </SessionProvider>
  )
}
