version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '2000:5432'
    env_file: $BASE_PATH/services/postgres/.env.development  
    volumes:
      - db_data_parkease:/var/lib/postgresql/data
volumes:
  db_data_parkease:
    