import { ApolloProvider } from '@parkease/network/src/config/apollo'
import '@parkease/ui/src/app/globals.css'
import { Container } from '@parkease/ui/src/components/atoms/Container'
import { SessionProvider } from '@parkease/ui/src/components/molecules/SessionProvider'
import { Header } from '@parkease/ui/src/components/organisms/Header'
import { MenuItem } from '@parkease/util/types'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Parkease | Manager',
  description: 'Generated by create next app',
}

const MENUITEMS: MenuItem[] = [
  { label: 'New Garage', href: '/new-garage' },
  { label: 'Valets', href: '/valets' },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <SessionProvider>
      <ApolloProvider>
        <html lang="en">
          <body className={`${inter.className} bg-gray-25`}>
            <Header menuItems={MENUITEMS} />
            <Container> {children}</Container>
          </body>
        </html>
      </ApolloProvider>
    </SessionProvider>
  )
}
