version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '2010:5432'
    env_file:
      - .env
    volumes:
      - db_data_parkease:/var/lib/postgresql/data
volumes:
  db_data_parkease:
